# PARTE 1: Introducción a NumPy

In [97]:
import numpy as np

## Vectores

In [98]:
vector = np.array([1,2,3,4,5,6])
print(vector)
# En numpy no hay manera de hacer un append sobre la misma lista por eso necesitamos crear otra
new_vector = np.append(vector,[10,20])
print(new_vector)

[1 2 3 4 5 6]
[ 1  2  3  4  5  6 10 20]


# Matrices

In [99]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)

# En numpy no podemos tener cosas de diferentes dimensiones
try:
    matriz_mala = np.array([[1,2,3],[4,5,]])
    print(matriz_mala)
except Exception as e:
    print(f"Error en la matriz: {e}")

[[1 2 3]
 [4 5 6]]
Error en la matriz: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.


# PARTE 2

In [100]:
arreglo = np.array([1,2,3,4,5,6])
print(arreglo)
# Se sigue manteniendo la misma manera de acceder a variables como en los arreglos de python
print(arreglo[2])


# Podemos modificar un elemento existente de algun indice pero no remover o agrar directamente
arreglo[2] = 777
print(arreglo)


# Podemos mantener el slicing de python nativo
print(arreglo[3:])
print(arreglo[::2])
print(arreglo[1:3])

[1 2 3 4 5 6]
3
[  1   2 777   4   5   6]
[4 5 6]
[  1 777   5]
[  2 777]


In [101]:
python_list: list[int] = [1,2,3,4,5,6]
python_slice: list[int] = python_list[:3]

python_slice[0] = 999
#  python crea un slicing copia no una referencia a la misma lista por ende la lista original jamas cambiará
print(python_slice)
print(python_list)

[999, 2, 3]
[1, 2, 3, 4, 5, 6]


In [102]:
numpy_list = np.array([1,2,3,4,5,6])
numpy_slice = numpy_list[:3]

numpy_slice[0] = 999

# Aquí aun que sea otra variable no se crea una copia independiente, por el contrario hacemos referencia a la lsita original en numpy
print(numpy_slice)
print(numpy_list)

[999   2   3]
[999   2   3   4   5   6]


In [103]:
matriz = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9] 
])

# Aquí accedemos a un selemnto de una matriz de 2D
print(matriz[1,2])

6


## Tipos de arrays en NumPy
- 0-D array = escalar
- 1-D array = vector
- 2-D array = matriz
- N-D array = tensor ( N significa número cualquiera mayor que 2)

# PARTE 3

In [104]:
arreglo = np.array([ [1,2,3], [4,5,6]], dtype=np.int16)

print(arreglo)


print(f"Dimensiones (dimensiones del arreglo): \n- {arreglo.ndim}")
print(f"Shape (tamaño que existe en cada dimensión del arreglo): \n- {arreglo.shape}")
print(f"Size (número total de elementos de este arreglo): \n- {arreglo.size}")
print(f"Tipo del arreglo  (se usa mucho para ver que tipo de datos guarda el arreglo): \n- {arreglo.dtype}")

[[1 2 3]
 [4 5 6]]
Dimensiones (dimensiones del arreglo): 
- 2
Shape (tamaño que existe en cada dimensión del arreglo): 
- (2, 3)
Size (número total de elementos de este arreglo): 
- 6
Tipo del arreglo  (se usa mucho para ver que tipo de datos guarda el arreglo): 
- int16


In [105]:
ones = np.zeros((3,5),dtype=int)
print(ones)
print(ones.dtype)

ones = np.ones((3,3,3),dtype=int)
print(ones)
print(ones.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int64
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
int64


In [106]:
vacio = np.empty((3,3))


# Ultra rapuido pero usa memoria y la reserva pero no la limpia
print(vacio)
print(vacio.dtype)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
float64


In [107]:
arreglo_rango = np.arange(10)
print(arreglo_rango)

arreglo_rango = np.arange(5,10)
print(arreglo_rango)

arreglo_rango = np.arange(0,20,2)
print(arreglo_rango)



[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [108]:
espaciado_lineal = np.linspace(0,10, num=3)
# Creamos un espaciado entre 0 al 10 de 3 separaciones  osea tendriamos el 0 como primer número y el 10 como ultimo pero hay un numero intermedio que hace de el 3cer separador
print(espaciado_lineal)

espaciado_lineal = np.linspace(0,10, num=5)
print(espaciado_lineal)

espaciado_lineal = np.linspace(0,10, num=20)
print(espaciado_lineal)

# Ponemos un typo de dato
espaciado_lineal = np.linspace(0,10, num=20, dtype=int)
print(espaciado_lineal)


espaciado_lineal = np.linspace(0,10, num=20, dtype=np.float16)
print(espaciado_lineal)


[ 0.  5. 10.]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[ 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9 10]
[ 0.      0.5264  1.053   1.579   2.105   2.63    3.158   3.684   4.21
  4.74    5.26    5.79    6.316   6.844   7.367   7.895   8.42    8.945
  9.48   10.    ]


# PARTE 4:

In [109]:
arreglo_desordenado = np.array([3, 2 ,10 , 1, 0])
arreglo_ordenado = np.sort(arreglo_desordenado)
print(arreglo_ordenado)

[ 0  1  2  3 10]


In [110]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
result = np.concatenate((a,b,c))
print(result)



a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9]])
result = np.concatenate((a,b))
print(result)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
arr = np.arange(10)
print(f"Original: \n{arr}")

arr = arr.reshape(2,5)
print(f"Reshape: \n{arr}")

arr = arr.reshape(5,2)
print(f"Reshape: \n{arr}")



arr = np.arange(27)
print(f"Original: \n{arr}")

arr = arr.reshape(1,9,3)
print(f"Reshape: \n{arr}")

arr = arr.reshape(3,3,3)
print(f"Reshape: \n{arr}")

arr = arr.reshape(-1) # El -1 en automatico convierte en 1D el arreglo que le pasemos
print(f"Reshape: \n{arr}")


Original: 
[0 1 2 3 4 5 6 7 8 9]
Reshape: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Reshape: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Original: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
Reshape: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]]
Reshape: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Reshape: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


# PARTE 5